github action: drop 7.6 since it errored
  Attempting to install ghc 7.6 using ghcup
  /opt/hostedtoolcache/ghcup/0.1.12/x64/ghcup install ghc 7.6
  [ Error ] No available GHC version for 7.6
Error: All install methods for ghc 7.6 failed